import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'

const Home: NextPage = () => {
  return (
    <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create Next App" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <button className="bg-blue-500"></button>

    </>
  )
}

export default Home;